sudo: false

language: ruby
cache: bundler

script:
  - echo "NOTHING"

deploy:
  skip_cleanup: true
  provider: script
  script:
    - bundle install && bundle exec wagon deploy -d -v production
  on:
    branch: master
